spring.application.name=locale-language
# Enable message source
spring.messages.basename=messages
spring.messages.cache-duration=3600
spring.messages.encoding=UTF-8

# Set default locale
spring.web.locale=en
spring.web.locale-resolver=accept-header