spring.application.name=locale-language
# Enable message source
spring.messages.basename=messages
spring.messages.cache-duration=3600
spring.messages.encoding=UTF-8

# Set default locale
spring.web.locale=en
spring.web.locale-resolver=accept-header


# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# Hibernate (JPA) Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Ensure UTF-8 Encoding
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'